version: '3'

services:
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  emgr:
    image: scorpiobroker/entity-manager:fanout-test
    env_file:
      - path: ./env.env
        required: true
    ports:
      - "1025:1025"
    depends_on:
      - postgres
  histemgr:
    image: scorpiobroker/history-entity-manager:fanout-test
    env_file:
      - path: ./env.env
        required: true
    ports:
      - "1040:1040"
    depends_on:
      - postgres
  histqmgr:
    image: scorpiobroker/history-query-manager:fanout-test
    env_file:
      - path: ./env.env
        required: true
    ports:
      - "1041:1041"
    depends_on:
      - postgres
  at-context-server:
    image: scorpiobroker/at-context-server:fanout-test
    env_file:
      - path: ./env.env
        required: true
    ports:
      - "1042:1042"
    depends_on:
      - postgres
  qrymgr:
    image: scorpiobroker/query-manager:fanout-test
    env_file:
      - path: ./env.env
        required: true
    ports:
      - "1026:1026"
    depends_on:
      - postgres
  regmgr:
    image: scorpiobroker/registry-manager:fanout-test
    env_file:
      - path: ./env.env
        required: true
    ports:
      - "1030:1030"
    depends_on:
      - postgres
  regsbsmgr:
    image: scorpiobroker/registry-subscription-manager:fanout-test
    env_file:
      - path: ./env.env
        required: true
    ports:
      - "2025:2025"
    depends_on:
      - postgres
  sbsmgr:
    image: scorpiobroker/subscription-manager:fanout-test
    env_file:
      - path: ./env.env
        required: true
    ports:
      - "2026:2026"
    depends_on:
      - postgres